version: '3'

services:
  elastic: 
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    env_file:
      - .env
    volumes:
      - ~/elastic-data:/usr/share/elasticsearch/data
    restart: on-failure

  server:
    build: ./
    volumes: 
      - ./dist:/usr/src/app/dist
    ports: 
      - 3005:3005
    env_file:
      - .env
    depends_on:
      - elastic
    restart: "no"